In [186]:
from datetime import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

In [58]:
%store -r X_train_bearish
%store -r X_test_bearish
%store -r X_train_bullish
%store -r X_test_bullish
%store -r Y_train_bearish
%store -r Y_test_bearish
%store -r Y_train_bullish
%store -r Y_test_bullish

%store -r trades_bearish
%store -r trades_bullish

*` Kmeans  `*

In [170]:
bearish_Kmeans = KMeans(n_clusters=5 ,init = 'k-means++', random_state= 1516 )
bearish_Kmeans.fit(X_train_bearish)
y_bearish_pred = bearish_Kmeans.predict(X_test_bearish)

In [171]:
unique, counts = np.unique(y_bearish_pred, return_counts=True)
print(np.asarray((unique, counts)).T)

[[  0 244]
 [  1 246]
 [  2 162]
 [  3 342]
 [  4  65]]


In [172]:

unique, counts = np.unique(y_bearish_pred, return_counts=True)
print(np.asarray((unique, counts)).T)

[[  0 244]
 [  1 246]
 [  2 162]
 [  3 342]
 [  4  65]]


In [173]:
bearish_test  = X_test_bearish.copy()
bearish_test['result'] = Y_test_bearish.values
bearish_test['lable'] = y_bearish_pred

In [174]:
bearish_labels=bearish_test.groupby(['lable','result'])[0].count()
bearish_wins = bearish_labels.loc[(slice(None),1)]
bearish_results=bearish_test.groupby(['lable'])[0].count()
bearish_lable_winrate = bearish_wins / bearish_results

In [175]:
bearish_labels

lable  result
0      0          92
       1         152
1      0          92
       1         154
2      0          47
       1         115
3      0         127
       1         215
4      0          19
       1          46
Name: 0, dtype: int64

In [178]:
bearish_lable_winrate

lable
0    0.622951
1    0.626016
2    0.709877
3    0.628655
4    0.707692
Name: 0, dtype: float64

In [179]:
bullish_Kmeans = KMeans(n_clusters=5 ,init = 'k-means++', random_state= 1516 ,max_iter=1000,n_init=100)
bullish_Kmeans.fit(X_train_bullish)
y_bullish_pred = bullish_Kmeans.predict(X_test_bullish)

In [180]:
bullish_test  = X_test_bullish.copy()
bullish_test['result'] = Y_test_bullish.values
bullish_test['lable'] = y_bullish_pred

In [181]:
bullish_labels=bullish_test.groupby(['lable','result'])[0].count()
bullish_wins = bullish_labels.loc[(slice(None),1)]
bullish_results=bullish_test.groupby(['lable'])[0].count()
bullish_lable_winrate = bullish_wins / bullish_results

In [182]:
bullish_labels

lable  result
0      0         161
       1         255
1      0         103
       1         171
2      0          36
       1          52
3      0          85
       1         158
4      1           1
Name: 0, dtype: int64

In [185]:
bullish_lable_winrate

lable
0    0.612981
1    0.624088
2    0.590909
3    0.650206
4    1.000000
Name: 0, dtype: float64

*` BDSCAN  `*

In [192]:
bearish_DBSCAN = DBSCAN(eps=4, min_samples=5)
bearish_DBSCAN.fit(X_train_bearish)
y_bearish_pred_DBSCAN = bearish_Kmeans.predict(X_test_bearish)

In [193]:
b_unique, b_counts = np.unique(y_bearish_pred_DBSCAN, return_counts=True)
print(np.asarray((b_unique, b_counts)).T)

[[  0 244]
 [  1 246]
 [  2 162]
 [  3 342]
 [  4  65]]
